### ISSUE TITLE
How to build gatk-micobialmode.jar?

### ISSUE THREAD

**Issue by garlandcrow** [broadinstitute/GATK-for-Microbes#22]
I was trying to run `MicrobialGenomePipeline.wdl` and my pipeline fails on lines like (line 284):

```
gatk --java-options "-Xmx2500m" ShiftFasta \
```

due to my `gatk` (when using default) not having some functions like `ShiftFasta`. I tried using the gatk override (like in the inputs.json in `shortReads` folder, but I don't have access to `gs://broad-dsp-spec-ops/scratch/andrea/gatk-microbialmode.jar`. Is there a branch of `gatk` that I should build that will have these functions or is that jar available somewhere else that has public access? Or maybe something else I am missing or didn't configure correctly that is causing this?

**Comment by jpn2021** [comment]
Did you have any success figuring this out?

**Comment by garlandcrow** [comment]
Yea, I saw a day or so after this issue there was some commits (maybe by coincidence) that changed the URLs used to access that file and that fixed it.

**Comment by jpn2021** [comment]
Weird. It doesn't seem to have changed when I look. Do you have the updated gs:// link?

**Comment by bhanugandham** [comment]
Hi all, apologies for the delay in getting back to you. The jar file was in a inaccessible bucket but going forward, the jar file will be located here: gs://gatk-best-practices/gatk-for-microbes/gatk-microbialmode.jar

**Comment by bhanugandham** [comment]
The workflow is updated with the latest jars and test files in this input.json file GATK-for-Microbes/wdl/shortReads/inputs.json

**Comment by bhanugandham** [comment]
We currently use two jar in the MicrobialGenomePipeline.wdl:
a) "MicrobialGenomePipeline.gatk_override":"gs://gatk-best-practices/gatk-for-microbes/gatk-microbialmode-prunerfix.jar",
b) "MicrobialGenomePipeline.ShiftReference.gatk_override":"gs://gatk-best-practices/gatk-for-microbes/gatk-microbialmode.jar" 

In the future commits this will be combined into one jar and  we will update the input.json accordingly.

**Comment by bhanugandham** [comment]
The workflow is updated with the latest jars and test files in this input.json file GATK-for-Microbes/wdl/shortReads/inputs.json
